# Sesi 4
Numpy

In [ ]:
import numpy as np

## Making Array

In [ ]:
firstArray = np.array([1,2,3,4])

In [5]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2, 10 , 2)

array([2, 4, 6, 8])

## Add,Remove, Sort

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
arr = np.append(arr, [1, 2])

In [18]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [21]:
np.sort(arr)

array([1, 1, 2, 2, 3, 4, 5, 6, 7, 8])

## Shape and Size

array_example = np.array([[[0, 1, 2, 3],
                         [0, 1 ,2 ,3]],
                          
                         [[0, 1 ,2 ,3],
                          [0, 1, 2, 3]],
                          
                          [[0, 1, 2, 3],
                          [0, 1, 2, 3]]])
                          

In [25]:
array_example

array([[[0, 1, 2, 3],
        [0, 1, 2, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3]],

       [[0, 1, 2, 3],
        [0, 1, 2, 3]]])

In [28]:
array_example.ndim

3

In [29]:
array_example.size

24

In [30]:
array_example.shape

(3, 2, 4)

## Reshape

In [31]:
a = np.arange (6)

In [32]:
a

array([0, 1, 2, 3, 4, 5])

In [33]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [34]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [36]:
a.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

## Convert 1D to 2D

In [37]:
a

array([0, 1, 2, 3, 4, 5])

In [38]:
a.shape

(6,)

In [40]:
a2 = a[np.newaxis]

In [41]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [43]:
a2.shape

(1, 6)

In [44]:
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [48]:
b2 = np.expand_dims(a, axis=1)

In [46]:
b3 = np.expand_dims(a, axis=0)

array([[0, 1, 2, 3, 4, 5]])

In [49]:
b2.shape

(6, 1)

## Indexing and Slicing

In [50]:
a

array([0, 1, 2, 3, 4, 5])

In [52]:
print(a)
print(a[0])
print(a[2])

[0 1 2 3 4 5]
0
2


In [53]:
a[0:4]

array([0, 1, 2, 3])

In [54]:
a[2:]

array([2, 3, 4, 5])

In [55]:
a[-1]

5

In [56]:
newArray = np.array([[1, 2, 3, 4,],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

In [57]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
newArray[newArray>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [59]:
newArray[newArray<5]

array([1, 2, 3, 4])

In [60]:
newArray[(newArray>2) & (newArray<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Creating Array from Existing Data

In [61]:
arr = np.arange(1, 11)

In [62]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr1 = arr[3: 8]

In [73]:
a_1 = np.array([[1,1],
              [2,2]])

In [74]:
a_2 = np.array([[2,2],
              [4,4]])

In [76]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [2, 2],
       [4, 4]])

In [77]:
np.hstack((a_1,a_2))

array([[1, 1, 2, 2],
       [2, 2, 4, 4]])

## Array Operations

In [78]:
data = np.array([1,2])

In [79]:
ones = np.ones(2)

In [80]:
data + ones

array([2., 3.])

In [81]:
data.sum()

3

In [82]:
a.sum()

15

In [83]:
b = np.array([[1,2],[2,2]])

In [84]:
b.sum()

7

In [86]:
b.sum(axis=0)

array([3, 4])

In [87]:
b.sum(axis=1)

array([3, 4])

In [88]:
data * 2

array([2, 4])

In [89]:
data =np.array([[1,2,3,4,5,6],
               [7,8,9,10,11,12],
                [13,14,15,16,17,18]])

In [90]:
data

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [91]:
data.sum()

171

In [92]:
data.sum(axis=0)

array([21, 24, 27, 30, 33, 36])

In [94]:
data.sum(axis=1)

array([21, 57, 93])

In [95]:
data.min()

1

In [96]:
data.max()

18

In [97]:
data.min(axis=1)

array([ 1,  7, 13])

In [98]:
data.min(axis=0)

array([1, 2, 3, 4, 5, 6])

## Matrices

In [99]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [100]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [103]:
np.random.random((4,5))

array([[0.40038322, 0.67907754, 0.39336257, 0.1215969 , 0.29239999],
       [0.51025632, 0.22841255, 0.20742315, 0.9140647 , 0.68215863],
       [0.41475781, 0.71873686, 0.63388688, 0.63826457, 0.69427633],
       [0.72854031, 0.27590944, 0.6386303 , 0.52754541, 0.24815509]])

In [104]:
data = np.array([[1,2], [3,4]])

In [106]:
ones = np.ones((2,2))

In [107]:
data

array([[1, 2],
       [3, 4]])

In [109]:
ones

array([[1., 1.],
       [1., 1.]])

In [111]:
data + ones

array([[2., 3.],
       [4., 5.]])

## Dot Product

In [112]:
a_1 = np.array([[1,2,3],[4,5,6]])

In [113]:
a_2 = np.array([[7,8],[9,10],[11,12]])

In [114]:
a_1

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
a_2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [116]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

## Indexing and Slicing

In [117]:
data = np.array([[1,2],[3,4],[5,6]])

In [118]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
data[0]

array([1, 2])

In [120]:
data[1]

array([3, 4])

In [121]:
data[0, 1]

2

In [122]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

## Transposing

In [123]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [124]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [125]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
data.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [128]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

## Flaten 